-- MOVED (Ola B2).
--
-- The RLS policies that used to live here are now a real, timestamped Prisma
-- migration applied automatically by `prisma migrate deploy`:
--
--     prisma/migrations/20260725120000_rls_policies/migration.sql
--
-- That migration is the single source of truth (17 original tables + 7 new
-- direct-tenant tables + Condition/Exercise split policies + Tenant UPDATE).
-- Do NOT add policies here — edit the migration (or add a new one) so the
-- drift guard (scripts/guard-tenant-isolation.mjs) stays green.
--
-- This file is kept only as a redirect; it is NOT applied by anything.
